---
resources:
- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    private_key: ((github-private-key))

- name: tags
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    private_key: ((github-private-key))
    tag_filter: "*"

- name: filtered-tags
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    private_key: ((github-private-key))
    tag_filter: "v*"

- name: tools
  type: git
  source:
    uri: ((tools-scripts-url))
    branch: ((tools-branch))

jobs:
- name: create-tag
  serial: false
  public: false
  plan:
  - aggregate:
    - get: repo
    - get: tools
  - task: create-tag
    privileged: true
    file: tools/task.yml
    params:
      MESSAGE: "Creating tag"
      SCRIPT_TO_RUN: "create_tag.sh"
      <<: *common-params
  - put: repo
    params:
      repository: out
      tag: out/tag
      only_tag: true

- name: delete-tag
  serial: false
  public: false
  plan:
  - aggregate:
    - get: tags
    - get: tools
  - task: delete-tag
    privileged: true
    file: tools/task.yml
    input_mapping:
      repo: tags
    params:
      MESSAGE: "Deleting tag"
      SCRIPT_TO_RUN: "delete_tag.sh"
      <<: *common-params
      GIT_PRIVATE_KEY: ((github-private-key))

- name: get-repo
  serial: false
  public: false
  plan:
  - aggregate:
    - get: repo
    - get: tools
  - task: echo-content
    privileged: true
    file: tools/task.yml
    params:
      MESSAGE: "Echo content"
      SCRIPT_TO_RUN: "echo_content.sh"
      <<: *common-params

- name: get-tags
  serial: false
  public: false
  plan:
  - aggregate:
    - get: tags
    - get: tools
  - task: echo-content
    privileged: true
    file: tools/task.yml
    input_mapping:
      repo: tags
    params:
      MESSAGE: "Echo content"
      SCRIPT_TO_RUN: "echo_content.sh"
      <<: *common-params

- name: get-filtered-tags
  serial: false
  public: false
  plan:
  - aggregate:
    - get: filtered-tags
    - get: tools
  - task: echo-content
    privileged: true
    file: tools/task.yml
    input_mapping:
      repo: filtered-tags
    params:
      MESSAGE: "Echo content"
      SCRIPT_TO_RUN: "echo_content.sh"
      <<: *common-params

common-params: &common-params
  GIT_EMAIL: ((git-email))
  GIT_NAME: ((git-name))
  PAAS_TYPE: ((paas-type))
  PIPELINE_VERSION: ((pipeline-version))
