---
resources:
- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    private_key: ((github-private-key))
    git_config:
      remote.origin.tagOpt: --no-tags

- name: tags
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    private_key: ((github-private-key))
    git_config:
      remote.origin.tagOpt: --tags
      push.followTags: "true"

- name: tools
  type: git
  source:
    uri: ((tools-scripts-url))
    branch: ((tools-branch))

jobs:
- name: create-tag
  serial: true
  public: false
  plan:
  - aggregate:
    - get: repo
    - get: tools
  - task: create-tag
    privileged: true
    file: tools/task.yml
    params:
      MESSAGE: "Creating tag"
      SCRIPT_TO_RUN: "create_tag.sh"
      <<: *common-params
  - put: repo
    params:
      repository: out
      tag: out/tag
      only_tag: true

- name: delete-tag
  serial: true
  public: false
  plan:
  - aggregate:
    - get: tags
    - get: tools
      passed:
      - create-tag
      trigger: true
  - task: delete-tag
    privileged: true
    file: tools/task.yml
    input_mapping:
      repo: tags
    params:
      MESSAGE: "Deleting tag"
      SCRIPT_TO_RUN: "delete_tag.sh"
      <<: *common-params
  - put: tags
    params:
      repository: tags
      only_tag: true

common-params: &common-params
  GIT_EMAIL: ((git-email))
  GIT_NAME: ((git-name))
  PAAS_TYPE: ((paas-type))
  PIPELINE_VERSION: ((pipeline-version))
